name: CI
on:
  workflow_dispatch:
  pull_request:
    type:
      - opened
      - synchronize
  push:
    branches:
      - main
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint
  test:
    name: Test code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Tests
        run: vitest run --coverage
